version: '3.6'
services:
  mysql:
    environment:
      - MYSQL_DATABASE=remote_config
      - MYSQL_ROOT_PASSWORD=pass
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
  api:
    container_name: "remote_config_ms"
    image: "remote_config_ms"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./wait-for-mysql.sh && ./docker-entrypoint-test.sh"
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules